### ISSUE TITLE
Using Chartist interpolation functions

### ISSUE THREAD

**Issue by mpvvliet** [nodef/chartist-svg#1]
Hi there,

thanks for creating such a useful library! 

I am looking for a way to use a Chartist-defined interpolation function, like so in the series-specific options:

```
  series: {
    remaining: {
      lineSmooth: Chartist.Interpolation.step(),
      showPoint: false
    }
```
Of course, Chartist itself including the Interpolation module can not be found. Including Chartist in my client code is also not working.

Is there a way to achieve this?

Thanks,
Martin

**Comment by wolfram77** [comment]
Oh i missed this. I came here after i got this notification: https://github.com/nodef/svgdom-css/pull/3
