### ISSUE TITLE
Chartist.Interpoation options not recognized 

### ISSUE THREAD

**Issue by tka85** [nodef/chartist-svg#7]
@wolfram77  Thanks upgrading package to Chartist v1.

I'm now passing as part of the `options`:

```
lineSmooth: Chartist.Interpolation.step()
```

but the generated SVG does not have step smoothing. Is that not supported or am I passing it wrong?

**Comment by wolfram77** [comment]
@tka85 I have updated the example to show how to pass options. You need to pass `lineSmooth` or any Chartist options within `chart` or `options` field of options. Do reopen if `v0.2.8` doesn't fix this issue.

![Screenshot (358)](https://github.com/nodef/chartist-svg/assets/3179612/52c0dee0-e26a-4b38-a196-4e9242ebf2f6)

**Comment by tka85** [comment]
Works great. Much appreciated!
