### ISSUE TITLE
Incompatible with typescript?

### ISSUE THREAD

**Issue by rzfzr** [nodef/chartist-svg#9]
Trying to run it on Electron's background

```
Module parse failed: Unexpected token (2187:2)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|   baseVal
|
>   constructor(element, attributeName) {
|     this.baseVal = new _SVGLength_js__WEBPACK_IMPORTED_MODULE_0__.SVGLength(element, attributeName)
|   }

 @ ./node_modules/svgdom-css/index.js 2:26-43
 @ ./node_modules/chartist-svg/index.js
 @ ./src/background.ts
 @ multi ./src/background.ts
```

**Comment by wolfram77** [comment]
Sorry, I forgot about this. In case you still face this issue, ping me here. @rzfzr

**Comment by rzfzr** [comment]
Hi, I believe it is still an issue yes, I didn't confirm if it was either the Electron's background environment, typescript, webpack, or something else, and probably won't myself.
I was on a exploratory phase of a project, so I just ended up using something else, d3js

**Comment by wolfram77** [comment]
Closing this old issue. Have a good day!
